import express, { Request, Response, NextFunction } from "express";
import cors from "cors";
import helmet from "helmet";
import swaggerUi from "swagger-ui-express";
import swaggerDoc from "../public/swagger.json";
import { ApplicationError, WrapperError } from "./errors";
import { env } from "./env";
import db from "./db";
import { RegisterRoutes } from "./routes"; // generated by tsoa

const app = express();
const PORT = env.PORT;

app.use(helmet({
  // Allow swagger UI inline styles/scripts
  contentSecurityPolicy: false,
}));
app.use(express.json());
app.use(
  cors({
    methods: ["GET", "POST", "PATCH", "DELETE"],
    allowedHeaders: ["Content-Type", "Authorization"],
  })
);

// --- Health ---
app.get("/health", (_req: Request, res: Response) => {
  res.json({ status: "ok" });
});

app.get("/ready", async (_req: Request, res: Response) => {
  const connected = await db.isConnected();
  if (connected) {
    res.json({ status: "ready", database: "connected" });
  } else {
    res.status(503).json({ status: "not_ready", database: "disconnected" });
  }
});

// --- Swagger UI ---
app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerDoc, {
  customCssUrl: "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css",
  customJs: [
    "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js",
    "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-standalone-preset.js",
  ],
}));
app.get("/docs.json", (_req: Request, res: Response) => {
  res.json(swaggerDoc);
});

// --- TSOA Generated Routes ---
RegisterRoutes(app);

// --- Error Handler (must be last) ---
app.use(
  (err: any, _req: Request, res: Response, _next: NextFunction): void => {
    if (err?.fields) {
      // TSOA ValidateError — request body/query/path validation failed
      res.status(err.status ?? 400).json({
        code: "VALIDATION_ERROR",
        message: "Validation failed",
        details: err.fields,
      });
    } else if (err?.error) {
      res.status(err.status ?? 500).json(err.error);
    } else if (err instanceof ApplicationError) {
      res.status(err.statusCode).json({ code: "APP_ERROR", message: err.message });
    } else if (err instanceof WrapperError) {
      res.status(err.statusCode).json({ code: "WRAPPED_ERROR", message: err.message });
    } else {
      console.error("Unexpected error:", err);
      res.status(500).json({ code: "SERVER_ERROR", message: "Internal Server Error" });
    }
  }
);

// Only bind to a port when running locally — Vercel handles this in production
if (!process.env.VERCEL) {
  app.listen(PORT, () => {
    console.log(`Fada Lustre API running on port ${PORT}`);
    console.log(`Swagger UI: http://localhost:${PORT}/docs`);
  });
}

export default app;
