import express, { Request, Response, NextFunction } from "express";
import cors from "cors";
import helmet from "helmet";
import swaggerUi from "swagger-ui-express";
import { ApplicationError, WrapperError } from "./errors";
import { env } from "./env";
import db from "./db";
import { RegisterRoutes } from "./routes"; // generated by tsoa

const app = express();
const PORT = env.PORT;

app.use(helmet({
  // Allow swagger UI inline styles/scripts
  contentSecurityPolicy: false,
}));
app.use(express.json());
app.use(
  cors({
    methods: ["GET", "POST", "PATCH", "DELETE"],
    allowedHeaders: ["Content-Type", "Authorization"],
  })
);

// --- Health ---
app.get("/health", (_req: Request, res: Response) => {
  res.json({ status: "ok" });
});

app.get("/ready", async (_req: Request, res: Response) => {
  const connected = await db.isConnected();
  if (connected) {
    res.json({ status: "ready", database: "connected" });
  } else {
    res.status(503).json({ status: "not_ready", database: "disconnected" });
  }
});

// --- Swagger UI ---
// eslint-disable-next-line @typescript-eslint/no-require-imports
const swaggerDoc = require("../public/swagger.json");
app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerDoc));
app.get("/docs.json", (_req: Request, res: Response) => {
  res.json(swaggerDoc);
});

// --- TSOA Generated Routes ---
RegisterRoutes(app);

// --- Error Handler (must be last) ---
app.use(
  (err: any, _req: Request, res: Response, _next: NextFunction): void => {
    if (err?.error) {
      // tsoa and controller-thrown structured errors
      res.status(err.status ?? 500).json(err.error);
    } else if (err instanceof ApplicationError) {
      res.status(err.statusCode).json({ code: "APP_ERROR", message: err.message });
    } else if (err instanceof WrapperError) {
      res.status(err.statusCode).json({ code: "WRAPPED_ERROR", message: err.message });
    } else {
      console.error("Unexpected error:", err);
      res.status(500).json({ code: "SERVER_ERROR", message: "Internal Server Error" });
    }
  }
);

app.listen(PORT, () => {
  console.log(`Fada Lustre API running on port ${PORT}`);
  console.log(`Swagger UI: http://localhost:${PORT}/docs`);
});
